name: Assign Issue on Comment

on:
  issue_comment:
    types: [created]

jobs:
  assign-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check Comment for /assign-me
        if: github.event.comment.body == '/assign-me'
        run: echo "::set-env name=ASSIGNEE::$(echo ${GITHUB_ACTOR})"

      - name: Assign Issue
        if: env.ASSIGNEE != ''
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const assignee = process.env.ASSIGNEE;
            const issueNumber = context.payload.issue.number;

            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              assignees: [assignee]
            });
