name: Comment on Pull Request Close

on:
  pull_request:
    types: [closed]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Comment on the closed pull request
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pr = context.payload.pull_request;
          const prCreator = pr.user.login;
          const prNumber = pr.number;
          
          const comment = `Hello @${prCreator}! Your pull request #${prNumber} has been closed. Thank you for your contribution to IndieKart!`;
          github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment,
          });
