name: Comment on PR Closure
on:
  pull_request_target:
    types:
      - closed

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on PR Closure
        uses: actions/github-script@v4
        with:
          
          script: |
            const { owner, repo, number } = context.issue;
            const commentAuthor = context.payload.pull_request.user.login;
            const commentBody = `Thank you  @${commentAuthor} , for your valuable time and contribution in our IndieKart 💗. \n It’s our IndieKart, so Let’s build this altogether !!🤝\n  Hoping to see you soon with another PR again 😇 \n Wishing you all the best for your journey into Open Source🚀
            `;
            await github.issues.createComment({ owner, repo, issue_number: number, body: commentBody });
            console.log(`Commented on the closed PR: ${commentBody}.`);
